server:
  port: 8761

eureka:
  instance:
    hostname: peer1
    metadata-map:
      zone: zone1
  server:
    remote-region-app-whitelist:
      region1: EUREKA-SERVICE,GATEWAY-REGION1
      region2: EUREKA-SERVICE,GATEWAY-REGION2
  client:
    region: region1
    service-url:
      defaultZone: http://peer2:8762/eureka
      zone2: http://peer2:8762/eureka
    availability-zones:
      region2: zone2
    fetch-registry: false
    fetch-remote-regions-registry: region2