server:
  port: 8762

eureka:
  instance:
    hostname: peer2
    metadata-map:
      zone: zone2
  server:
    remote-region-app-whitelist:
      region1: EUREKA-SERVICE,GATEWAY-REGION1
      region2: EUREKA-SERVICE,GATEWAY-REGION2
  client:
    region: region2
    service-url:
      defaultZone: http://peer1:8761/eureka
      zone1: http://peer1:8761/eureka
    availability-zones:
      region1: zone1
    fetch-registry: false
    fetch-remote-regions-registry: region1